/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { EndpointService } from "../endpoint.service";
import { EndpointCreateInput } from "./EndpointCreateInput";
import { Endpoint } from "./Endpoint";
import { EndpointFindManyArgs } from "./EndpointFindManyArgs";
import { EndpointWhereUniqueInput } from "./EndpointWhereUniqueInput";
import { EndpointUpdateInput } from "./EndpointUpdateInput";

export class EndpointControllerBase {
  constructor(protected readonly service: EndpointService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Endpoint })
  async createEndpoint(
    @common.Body() data: EndpointCreateInput
  ): Promise<Endpoint> {
    return await this.service.createEndpoint({
      data: data,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Endpoint] })
  @ApiNestedQuery(EndpointFindManyArgs)
  async endpoints(@common.Req() request: Request): Promise<Endpoint[]> {
    const args = plainToClass(EndpointFindManyArgs, request.query);
    return this.service.endpoints({
      ...args,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Endpoint })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async endpoint(
    @common.Param() params: EndpointWhereUniqueInput
  ): Promise<Endpoint | null> {
    const result = await this.service.endpoint({
      where: params,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Endpoint })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateEndpoint(
    @common.Param() params: EndpointWhereUniqueInput,
    @common.Body() data: EndpointUpdateInput
  ): Promise<Endpoint | null> {
    try {
      return await this.service.updateEndpoint({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          typeField: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Endpoint })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteEndpoint(
    @common.Param() params: EndpointWhereUniqueInput
  ): Promise<Endpoint | null> {
    try {
      return await this.service.deleteEndpoint({
        where: params,
        select: {
          createdAt: true,
          id: true,
          typeField: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
