/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { EnumQueueItemQueueItemStatus } from "./EnumQueueItemQueueItemStatus";
import { EnumQueueItemQueueStatusType } from "./EnumQueueItemQueueStatusType";
import { EnumQueueItemStatus } from "./EnumQueueItemStatus";
import { EnumQueueItemStatusTypeQueueItem } from "./EnumQueueItemStatusTypeQueueItem";

@InputType()
class QueueItemWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  content?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  queueContent?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumQueueItemQueueItemStatus,
  })
  @IsEnum(EnumQueueItemQueueItemStatus)
  @IsOptional()
  @Field(() => EnumQueueItemQueueItemStatus, {
    nullable: true,
  })
  queueItemStatus?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumQueueItemQueueStatusType,
  })
  @IsEnum(EnumQueueItemQueueStatusType)
  @IsOptional()
  @Field(() => EnumQueueItemQueueStatusType, {
    nullable: true,
  })
  queueStatusType?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumQueueItemStatus,
  })
  @IsEnum(EnumQueueItemStatus)
  @IsOptional()
  @Field(() => EnumQueueItemStatus, {
    nullable: true,
  })
  status?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumQueueItemStatusTypeQueueItem,
  })
  @IsEnum(EnumQueueItemStatusTypeQueueItem)
  @IsOptional()
  @Field(() => EnumQueueItemStatusTypeQueueItem, {
    nullable: true,
  })
  statusTypeQueueItem?: "Option1";
}

export { QueueItemWhereInput as QueueItemWhereInput };
