/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsDate, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { EnumQueueItemQueueItemStatus } from "./EnumQueueItemQueueItemStatus";
import { EnumQueueItemQueueStatusType } from "./EnumQueueItemQueueStatusType";
import { EnumQueueItemStatus } from "./EnumQueueItemStatus";
import { EnumQueueItemStatusTypeQueueItem } from "./EnumQueueItemStatusTypeQueueItem";

@ObjectType()
class QueueItem {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  queueContent!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumQueueItemQueueItemStatus,
  })
  @IsEnum(EnumQueueItemQueueItemStatus)
  @IsOptional()
  @Field(() => EnumQueueItemQueueItemStatus, {
    nullable: true,
  })
  queueItemStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumQueueItemQueueStatusType,
  })
  @IsEnum(EnumQueueItemQueueStatusType)
  @IsOptional()
  @Field(() => EnumQueueItemQueueStatusType, {
    nullable: true,
  })
  queueStatusType?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumQueueItemStatus,
  })
  @IsEnum(EnumQueueItemStatus)
  @IsOptional()
  @Field(() => EnumQueueItemStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumQueueItemStatusTypeQueueItem,
  })
  @IsEnum(EnumQueueItemStatusTypeQueueItem)
  @IsOptional()
  @Field(() => EnumQueueItemStatusTypeQueueItem, {
    nullable: true,
  })
  statusTypeQueueItem?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { QueueItem as QueueItem };
